[build]
command = "dotnet workload install wasm-tools && dotnet publish BlazorCodeChallenge.csproj -c Release"
publish = "bin/Release/net8.0/publish/wwwroot"

[build.environment]
DOTNET_VERSION = "8.0.128"

[[edge_functions]]
function = "tmdb"
path = "/tmdb/*"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200