@BlazorCodeChallenge.EnterpriseApi_HostAddress = http://localhost:5209

GET {{BlazorCodeChallenge.EnterpriseApi_HostAddress}}/api/engineering/status
Accept: application/json

###

GET {{BlazorCodeChallenge.EnterpriseApi_HostAddress}}/api/engineering/diagnostics
Accept: application/json

###
